apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: juice-shop
  annotations:
    github.com/project-slug: Ali-Yazdani/juice-shop
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: unknown
  owner: team-a
